name: Sync on DOM Cloud
"on":
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Invoke SGA deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL_SGA }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET_SGA }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH_SGA }}
          data: >-
            {"commands":["git pull","npm i","sudo systemctl restart bridge"]}
